[apio]
default-env = tang9k
; default-env = tang20k
; default-env = icefun

[common]
top-module = main
default-testbench = main_tb.v

format-verible-options =
    --column_limit=100
    --indentation_spaces=2

nextpnr-extra-options =
    --seed 1008

gtkwave-extra-options =
    --rcvar=do_initial_zoom_fit 0
 
[env:tang20k]
board = sipeed-tang-nano-20k
constraint-file = tang20k-pinout.cst

[env:tang9k]
board = sipeed-tang-nano-9k
constraint-file = tang9k-pinout.cst

[env:icefun]
board = icefun
constraint-file = icefun-pinout.pcf
