/* Generated by Yosys 0.61+112 (git sha1 ac427a79b-dirty, aarch64-apple-darwin23.5-clang++ 18.1.8 -fPIC -O3) */





module main (
    sys_clk,
    probe_clk,
    probe_rd_en,
    probe_mem_out,
    probe_reg_out
);

  input sys_clk;
  wire sys_clk;

  output probe_clk;
  wire probe_clk;

  output probe_rd_en;
  wire probe_rd_en;

  output probe_mem_out;
  wire probe_mem_out;

  output probe_reg_out;
  wire probe_reg_out;


  wire [1:0] \mem.0.0_ADA ;


  wire [7:0] \mem.0.0_ADA_LUT2_I1_F ;
  wire \mem.0.0_CEA ;
  wire \mem.0.0_DIA ;
  wire [7:0] \mem.0.0_DIA_1 ;


  wire [17:0] \mem.0.0_DOA ;

  wire [8:0] \mem.0.0_DOA_1 ;


  wire [17:0] \mem.0.0_DOB ;

  wire [8:0] \mem.0.0_DOB_1 ;

  wire [7:0] \mem.0.0_DOB_2 ;


  wire [2:0] \mem.0.0_DOB_3 ;
  wire \mem.0.0_DOB_3_DFFE_Q_1_D ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ;

  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ;

  wire [7:0] rd_addr;
  wire rd_addr_DFFE_Q_D;

  wire [7:0] rd_data;

  wire rd_en;
  wire rd_en_DFFE_Q_CE;

  wire rd_en_DFFE_Q_CE_MUX2_LUT5_O_I0;
  wire rd_en_DFFE_Q_D;


  wire rd_en_DFFE_Q_D_ALU_SUM_CIN;


  wire rd_en_DFFE_Q_D_ALU_SUM_COUT;


  wire rd_en_DFFE_Q_D_ALU_SUM_COUT_ALU_CIN_COUT;
  wire sys_clk_IBUF_I_O;

  wire [7:0] wr_addr;
  wire wr_addr_DFFR_Q_1_D;


  wire wr_addr_DFFR_Q_1_D_ALU_SUM_COUT;
  wire wr_addr_DFFR_Q_2_D;


  wire wr_addr_DFFR_Q_2_D_ALU_SUM_COUT;
  wire wr_addr_DFFR_Q_3_D;


  wire wr_addr_DFFR_Q_3_D_ALU_SUM_COUT;
  wire wr_addr_DFFR_Q_4_D;


  wire wr_addr_DFFR_Q_4_D_ALU_SUM_COUT;
  wire wr_addr_DFFR_Q_5_D;


  wire wr_addr_DFFR_Q_5_D_ALU_SUM_COUT;
  wire wr_addr_DFFR_Q_6_D;


  wire wr_addr_DFFR_Q_6_D_ALU_SUM_CIN;

  wire wr_addr_DFFR_Q_6_D_ALU_SUM_CIN_ALU_COUT_SUM;


  wire wr_addr_DFFR_Q_6_D_ALU_SUM_COUT;
  wire wr_addr_DFFR_Q_7_D;
  wire wr_addr_DFFR_Q_D;



  wire wr_addr_DFFR_Q_D_ALU_SUM_COUT;


  wire [4:0] wr_addr_LUT4_I0_1_F;

  wire wr_addr_LUT4_I0_F;

  wire [7:0] wr_data;
  wire wr_data_DFFE_Q_1_D;
  wire wr_data_DFFE_Q_2_D;
  wire wr_data_DFFE_Q_3_D;


  wire wr_data_DFFE_Q_3_D_ALU_SUM_COUT;
  wire wr_data_DFFE_Q_4_D;


  wire wr_data_DFFE_Q_4_D_ALU_SUM_COUT;
  wire wr_data_DFFE_Q_5_D;


  wire wr_data_DFFE_Q_5_D_ALU_SUM_CIN;

  wire wr_data_DFFE_Q_5_D_ALU_SUM_CIN_ALU_COUT_SUM;


  wire wr_data_DFFE_Q_5_D_ALU_SUM_COUT;
  wire wr_data_DFFE_Q_6_D;
  wire wr_data_DFFE_Q_D;



  wire wr_data_DFFE_Q_D_ALU_SUM_COUT;


  DPX9B #(
      .BIT_WIDTH_0(32'd9),
      .BIT_WIDTH_1(32'd9),
      .BLK_SEL_0  (3'h0),
      .BLK_SEL_1  (3'h0),
      .INIT_RAM_00(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_01(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_02(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_03(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_04(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_05(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_06(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_07(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_08(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_09(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_0A(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_0B(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_0C(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_0D(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_0E(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_0F(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_10(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_11(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_12(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_13(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_14(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_15(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_16(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_17(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_18(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_19(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_1A(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_1B(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_1C(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_1D(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_1E(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_1F(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_20(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_21(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_22(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_23(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_24(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_25(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_26(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_27(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_28(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_29(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_2A(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_2B(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_2C(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_2D(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_2E(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_2F(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_30(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_31(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_32(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_33(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_34(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_35(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_36(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_37(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_38(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_39(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_3A(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_3B(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_3C(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_3D(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_3E(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .INIT_RAM_3F(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
      .READ_MODE0 (1'h0),
      .READ_MODE1 (1'h0),
      .RESET_MODE ("ASYNC"),
      .WRITE_MODE0(32'd2),
      .WRITE_MODE1(32'd2)
  ) \mem.0.0 (
      .ADA({
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        \mem.0.0_ADA_LUT2_I1_F [0],
        \mem.0.0_ADA_LUT2_I1_F [1],
        \mem.0.0_ADA_LUT2_I1_F [2],
        \mem.0.0_ADA_LUT2_I1_F [3],
        \mem.0.0_ADA_LUT2_I1_F [4],
        \mem.0.0_ADA_LUT2_I1_F [5],
        \mem.0.0_ADA_LUT2_I1_F [6],
        \mem.0.0_ADA [1],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7]
      }),
      .ADB({
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[0],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7]
      }),
      .BLKSELA({rd_addr[7], rd_addr[7], rd_addr[7]}),
      .BLKSELB({rd_addr[7], rd_addr[7], rd_addr[7]}),
      .CEA(\mem.0.0_CEA ),
      .CEB(rd_en),
      .CLKA(sys_clk_IBUF_I_O),
      .CLKB(sys_clk_IBUF_I_O),
      .DIA({
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        1'hx,
        \mem.0.0_DIA_1 [7:1],
        \mem.0.0_DIA
      }),
      .DIB({
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        rd_addr[7],
        9'hxxx
      }),
      .DOA({\mem.0.0_DOA [17:9], \mem.0.0_DOA_1 }),
      .DOB({\mem.0.0_DOB [17:9], \mem.0.0_DOB_1 [8], \mem.0.0_DOB_2 [7:1], \mem.0.0_DOB_3 [0]}),
      .OCEA(\mem.0.0_CEA ),
      .OCEB(\mem.0.0_CEA ),
      .RESETA(rd_addr[7]),
      .RESETB(rd_addr[7]),
      .WREA(\mem.0.0_CEA ),
      .WREB(rd_addr[7])
  );


  DFF \mem.0.0_ADA_DFF_Q (
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_addr[0]),
      .Q  (\mem.0.0_ADA [1])
  );


  LUT2 #(
      .INIT(4'h9)
  ) \mem.0.0_ADA_LUT2_I1 (
      .F (\mem.0.0_ADA_LUT2_I1_F [7]),
      .I0(rd_addr[0]),
      .I1(\mem.0.0_ADA [1])
  );


  DFF \mem.0.0_ADA_LUT2_I1_F_DFF_Q (
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_addr[7]),
      .Q  (\mem.0.0_ADA_LUT2_I1_F [0])
  );


  DFF \mem.0.0_ADA_LUT2_I1_F_DFF_Q_1 (
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_addr[6]),
      .Q  (\mem.0.0_ADA_LUT2_I1_F [1])
  );


  DFF \mem.0.0_ADA_LUT2_I1_F_DFF_Q_2 (
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_addr[5]),
      .Q  (\mem.0.0_ADA_LUT2_I1_F [2])
  );


  DFF \mem.0.0_ADA_LUT2_I1_F_DFF_Q_3 (
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_addr[4]),
      .Q  (\mem.0.0_ADA_LUT2_I1_F [3])
  );


  DFF \mem.0.0_ADA_LUT2_I1_F_DFF_Q_4 (
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_addr[3]),
      .Q  (\mem.0.0_ADA_LUT2_I1_F [4])
  );


  DFF \mem.0.0_ADA_LUT2_I1_F_DFF_Q_5 (
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_addr[2]),
      .Q  (\mem.0.0_ADA_LUT2_I1_F [5])
  );


  DFF \mem.0.0_ADA_LUT2_I1_F_DFF_Q_6 (
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_addr[1]),
      .Q  (\mem.0.0_ADA_LUT2_I1_F [6])
  );
  VCC \mem.0.0_CEA_VCC_V (.V(\mem.0.0_CEA ));


  DFF \mem.0.0_DIA_1_DFF_Q (
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_data[7]),
      .Q  (\mem.0.0_DIA_1 [7])
  );


  DFF \mem.0.0_DIA_1_DFF_Q_1 (
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_data[6]),
      .Q  (\mem.0.0_DIA_1 [6])
  );


  DFF \mem.0.0_DIA_1_DFF_Q_2 (
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_data[4]),
      .Q  (\mem.0.0_DIA_1 [4])
  );


  DFF \mem.0.0_DIA_1_DFF_Q_3 (
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_data[3]),
      .Q  (\mem.0.0_DIA_1 [3])
  );


  DFF \mem.0.0_DIA_1_DFF_Q_4 (
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_data[2]),
      .Q  (\mem.0.0_DIA_1 [2])
  );


  DFF \mem.0.0_DIA_1_DFF_Q_5 (
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_data[1]),
      .Q  (\mem.0.0_DIA_1 [1])
  );


  DFF \mem.0.0_DIA_DFF_Q (
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_data[0]),
      .Q  (\mem.0.0_DIA )
  );


  DFFE \mem.0.0_DOB_3_DFFE_Q (
      .CE (rd_en),
      .CLK(sys_clk_IBUF_I_O),
      .D  (\mem.0.0_DIA ),
      .Q  (\mem.0.0_DOB_3 [1])
  );


  DFFE \mem.0.0_DOB_3_DFFE_Q_1 (
      .CE (rd_en),
      .CLK(sys_clk_IBUF_I_O),
      .D  (\mem.0.0_DOB_3_DFFE_Q_1_D ),
      .Q  (\mem.0.0_DOB_3 [2])
  );


  MUX2_LUT8 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O (
      .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0 ),
      .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1 ),
      .O (\mem.0.0_DOB_3_DFFE_Q_1_D ),
      .S0(\mem.0.0_ADA_LUT2_I1_F [7])
  );


  MUX2_LUT7 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O (
      .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0 ),
      .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1 ),
      .O (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0 ),
      .S0(\mem.0.0_ADA_LUT2_I1_F [6])
  );


  MUX2_LUT6 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O (
      .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ),
      .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ),
      .O (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0 ),
      .S0(\mem.0.0_ADA_LUT2_I1_F [5])
  );


  MUX2_LUT5 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O (
      .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
      .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
      .O (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ),
      .S0(\mem.0.0_ADA_LUT2_I1_F [4])
  );


  LUT1 #(
      .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F (
      .F (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
      .I0(rd_addr[7])
  );


  LUT1 #(
      .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F (
      .F (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
      .I0(rd_addr[7])
  );


  MUX2_LUT5 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O (
      .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
      .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
      .O (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ),
      .S0(\mem.0.0_ADA_LUT2_I1_F [4])
  );


  LUT1 #(
      .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F (
      .F (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
      .I0(rd_addr[7])
  );


  LUT1 #(
      .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F (
      .F (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
      .I0(rd_addr[7])
  );


  MUX2_LUT6 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O (
      .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ),
      .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ),
      .O (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1 ),
      .S0(\mem.0.0_ADA_LUT2_I1_F [5])
  );


  MUX2_LUT5 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O (
      .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
      .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
      .O (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ),
      .S0(\mem.0.0_ADA_LUT2_I1_F [4])
  );


  LUT1 #(
      .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F (
      .F (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
      .I0(rd_addr[7])
  );


  LUT1 #(
      .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F (
      .F (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
      .I0(rd_addr[7])
  );


  MUX2_LUT5 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O (
      .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
      .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
      .O (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ),
      .S0(\mem.0.0_ADA_LUT2_I1_F [4])
  );


  LUT1 #(
      .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F (
      .F (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
      .I0(rd_addr[7])
  );


  LUT1 #(
      .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F (
      .F (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
      .I0(rd_addr[7])
  );


  MUX2_LUT7 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O (
      .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0 ),
      .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1 ),
      .O (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1 ),
      .S0(\mem.0.0_ADA_LUT2_I1_F [6])
  );


  MUX2_LUT6 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O (
      .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ),
      .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ),
      .O (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0 ),
      .S0(\mem.0.0_ADA_LUT2_I1_F [5])
  );


  MUX2_LUT5 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O (
      .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
      .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
      .O (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ),
      .S0(\mem.0.0_ADA_LUT2_I1_F [4])
  );


  LUT4 #(
      .INIT(16'h0001)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT4_F (
      .F (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
      .I0(\mem.0.0_ADA_LUT2_I1_F [0]),
      .I1(\mem.0.0_ADA_LUT2_I1_F [1]),
      .I2(\mem.0.0_ADA_LUT2_I1_F [2]),
      .I3(\mem.0.0_ADA_LUT2_I1_F [3])
  );


  LUT1 #(
      .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F (
      .F (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
      .I0(rd_addr[7])
  );


  MUX2_LUT5 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O (
      .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
      .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
      .O (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ),
      .S0(\mem.0.0_ADA_LUT2_I1_F [4])
  );


  LUT1 #(
      .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F (
      .F (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
      .I0(rd_addr[7])
  );


  LUT1 #(
      .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F (
      .F (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
      .I0(rd_addr[7])
  );


  MUX2_LUT6 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O (
      .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ),
      .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ),
      .O (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1 ),
      .S0(\mem.0.0_ADA_LUT2_I1_F [5])
  );


  MUX2_LUT5 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O (
      .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
      .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
      .O (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ),
      .S0(\mem.0.0_ADA_LUT2_I1_F [4])
  );


  LUT1 #(
      .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F (
      .F (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
      .I0(rd_addr[7])
  );


  LUT1 #(
      .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F (
      .F (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
      .I0(rd_addr[7])
  );


  MUX2_LUT5 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O (
      .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
      .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
      .O (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ),
      .S0(\mem.0.0_ADA_LUT2_I1_F [4])
  );


  LUT1 #(
      .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F (
      .F (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
      .I0(rd_addr[7])
  );


  LUT1 #(
      .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F (
      .F (\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
      .I0(rd_addr[7])
  );

  OBUF probe_clk_OBUF_O (
      .I(sys_clk_IBUF_I_O),
      .O(probe_clk)
  );

  OBUF probe_mem_out_OBUF_O (
      .I(rd_addr[7]),
      .O(probe_mem_out)
  );

  OBUF probe_rd_en_OBUF_O (
      .I(wr_data[7]),
      .O(probe_rd_en)
  );

  OBUF probe_reg_out_OBUF_O (
      .I(rd_data[0]),
      .O(probe_reg_out)
  );


  DFFE rd_addr_DFFE_Q (
      .CE (rd_en),
      .CLK(sys_clk_IBUF_I_O),
      .D  (rd_addr_DFFE_Q_D),
      .Q  (rd_addr[0])
  );


  LUT1 #(
      .INIT(2'h1)
  ) rd_addr_DFFE_Q_D_LUT1_F (
      .F (rd_addr_DFFE_Q_D),
      .I0(rd_addr[0])
  );
  GND rd_addr_GND_G (.G(rd_addr[7]));


  LUT3 #(
      .INIT(8'hca)
  ) rd_data_LUT3_F (
      .F (rd_data[0]),
      .I0(\mem.0.0_DOB_3 [0]),
      .I1(\mem.0.0_DOB_3 [1]),
      .I2(\mem.0.0_DOB_3 [2])
  );


  DFFE rd_en_DFFE_Q (
      .CE (rd_en_DFFE_Q_CE),
      .CLK(sys_clk_IBUF_I_O),
      .D  (rd_en_DFFE_Q_D),
      .Q  (rd_en)
  );


  MUX2_LUT5 rd_en_DFFE_Q_CE_MUX2_LUT5_O (
      .I0(rd_en_DFFE_Q_CE_MUX2_LUT5_O_I0),
      .I1(wr_addr_LUT4_I0_F),
      .O (rd_en_DFFE_Q_CE),
      .S0(wr_addr_LUT4_I0_1_F[4])
  );


  LUT1 #(
      .INIT(2'h0)
  ) rd_en_DFFE_Q_CE_MUX2_LUT5_O_I0_LUT1_F (
      .F (rd_en_DFFE_Q_CE_MUX2_LUT5_O_I0),
      .I0(rd_addr[7])
  );


  ALU #(
      .ALU_MODE(32'sd2)
  ) rd_en_DFFE_Q_D_ALU_SUM (
      .CIN (rd_en_DFFE_Q_D_ALU_SUM_CIN),
      .COUT(rd_en_DFFE_Q_D_ALU_SUM_COUT),
      .I0  (rd_addr[7]),
      .I1  (rd_en),
      .I3  (\mem.0.0_CEA ),
      .SUM (rd_en_DFFE_Q_D)
  );


  ALU #(
      .ALU_MODE(32'sd2)
  ) rd_en_DFFE_Q_D_ALU_SUM_COUT_ALU_CIN (
      .CIN (rd_en_DFFE_Q_D_ALU_SUM_COUT),
      .COUT(rd_en_DFFE_Q_D_ALU_SUM_COUT_ALU_CIN_COUT),
      .I0  (rd_addr[7]),
      .I1  (wr_data[6]),
      .I3  (\mem.0.0_CEA ),
      .SUM (wr_data_DFFE_Q_1_D)
  );


  DFF rd_en_DFF_D (
      .CLK(sys_clk_IBUF_I_O),
      .D  (rd_en),
      .Q  (\mem.0.0_DIA_1 [5])
  );

  IBUF sys_clk_IBUF_I (
      .I(sys_clk),
      .O(sys_clk_IBUF_I_O)
  );


  DFFR wr_addr_DFFR_Q (
      .CLK(sys_clk_IBUF_I_O),
      .D(wr_addr_DFFR_Q_D),
      .Q(wr_addr[7]),
      .RESET(rd_en_DFFE_Q_CE)
  );


  DFFR wr_addr_DFFR_Q_1 (
      .CLK(sys_clk_IBUF_I_O),
      .D(wr_addr_DFFR_Q_1_D),
      .Q(wr_addr[6]),
      .RESET(rd_en_DFFE_Q_CE)
  );


  ALU #(
      .ALU_MODE(32'sd2)
  ) wr_addr_DFFR_Q_1_D_ALU_SUM (
      .CIN (wr_addr_DFFR_Q_2_D_ALU_SUM_COUT),
      .COUT(wr_addr_DFFR_Q_1_D_ALU_SUM_COUT),
      .I0  (rd_addr[7]),
      .I1  (wr_addr[6]),
      .I3  (\mem.0.0_CEA ),
      .SUM (wr_addr_DFFR_Q_1_D)
  );


  DFFR wr_addr_DFFR_Q_2 (
      .CLK(sys_clk_IBUF_I_O),
      .D(wr_addr_DFFR_Q_2_D),
      .Q(wr_addr[5]),
      .RESET(rd_en_DFFE_Q_CE)
  );


  ALU #(
      .ALU_MODE(32'sd2)
  ) wr_addr_DFFR_Q_2_D_ALU_SUM (
      .CIN (wr_addr_DFFR_Q_3_D_ALU_SUM_COUT),
      .COUT(wr_addr_DFFR_Q_2_D_ALU_SUM_COUT),
      .I0  (rd_addr[7]),
      .I1  (wr_addr[5]),
      .I3  (\mem.0.0_CEA ),
      .SUM (wr_addr_DFFR_Q_2_D)
  );


  DFFR wr_addr_DFFR_Q_3 (
      .CLK(sys_clk_IBUF_I_O),
      .D(wr_addr_DFFR_Q_3_D),
      .Q(wr_addr[4]),
      .RESET(rd_en_DFFE_Q_CE)
  );


  ALU #(
      .ALU_MODE(32'sd2)
  ) wr_addr_DFFR_Q_3_D_ALU_SUM (
      .CIN (wr_addr_DFFR_Q_4_D_ALU_SUM_COUT),
      .COUT(wr_addr_DFFR_Q_3_D_ALU_SUM_COUT),
      .I0  (rd_addr[7]),
      .I1  (wr_addr[4]),
      .I3  (\mem.0.0_CEA ),
      .SUM (wr_addr_DFFR_Q_3_D)
  );


  DFFR wr_addr_DFFR_Q_4 (
      .CLK(sys_clk_IBUF_I_O),
      .D(wr_addr_DFFR_Q_4_D),
      .Q(wr_addr[3]),
      .RESET(rd_en_DFFE_Q_CE)
  );


  ALU #(
      .ALU_MODE(32'sd2)
  ) wr_addr_DFFR_Q_4_D_ALU_SUM (
      .CIN (wr_addr_DFFR_Q_5_D_ALU_SUM_COUT),
      .COUT(wr_addr_DFFR_Q_4_D_ALU_SUM_COUT),
      .I0  (rd_addr[7]),
      .I1  (wr_addr[3]),
      .I3  (\mem.0.0_CEA ),
      .SUM (wr_addr_DFFR_Q_4_D)
  );


  DFFR wr_addr_DFFR_Q_5 (
      .CLK(sys_clk_IBUF_I_O),
      .D(wr_addr_DFFR_Q_5_D),
      .Q(wr_addr[2]),
      .RESET(rd_en_DFFE_Q_CE)
  );


  ALU #(
      .ALU_MODE(32'sd2)
  ) wr_addr_DFFR_Q_5_D_ALU_SUM (
      .CIN (wr_addr_DFFR_Q_6_D_ALU_SUM_COUT),
      .COUT(wr_addr_DFFR_Q_5_D_ALU_SUM_COUT),
      .I0  (rd_addr[7]),
      .I1  (wr_addr[2]),
      .I3  (\mem.0.0_CEA ),
      .SUM (wr_addr_DFFR_Q_5_D)
  );


  DFFR wr_addr_DFFR_Q_6 (
      .CLK(sys_clk_IBUF_I_O),
      .D(wr_addr_DFFR_Q_6_D),
      .Q(wr_addr[1]),
      .RESET(rd_en_DFFE_Q_CE)
  );


  ALU #(
      .ALU_MODE(32'sd2)
  ) wr_addr_DFFR_Q_6_D_ALU_SUM (
      .CIN (wr_addr_DFFR_Q_6_D_ALU_SUM_CIN),
      .COUT(wr_addr_DFFR_Q_6_D_ALU_SUM_COUT),
      .I0  (rd_addr[7]),
      .I1  (wr_addr[1]),
      .I3  (\mem.0.0_CEA ),
      .SUM (wr_addr_DFFR_Q_6_D)
  );


  ALU #(
      .ALU_MODE(32'sd2)
  ) wr_addr_DFFR_Q_6_D_ALU_SUM_CIN_ALU_COUT (
      .CIN (rd_addr[7]),
      .COUT(wr_addr_DFFR_Q_6_D_ALU_SUM_CIN),
      .I0  (\mem.0.0_CEA ),
      .I1  (wr_addr[0]),
      .I3  (\mem.0.0_CEA ),
      .SUM (wr_addr_DFFR_Q_6_D_ALU_SUM_CIN_ALU_COUT_SUM)
  );


  DFFR wr_addr_DFFR_Q_7 (
      .CLK(sys_clk_IBUF_I_O),
      .D(wr_addr_DFFR_Q_7_D),
      .Q(wr_addr[0]),
      .RESET(rd_en_DFFE_Q_CE)
  );


  LUT1 #(
      .INIT(2'h1)
  ) wr_addr_DFFR_Q_7_D_LUT1_F (
      .F (wr_addr_DFFR_Q_7_D),
      .I0(wr_addr[0])
  );


  ALU #(
      .ALU_MODE(32'sd2)
  ) wr_addr_DFFR_Q_D_ALU_SUM (
      .CIN (wr_addr_DFFR_Q_1_D_ALU_SUM_COUT),
      .COUT(wr_addr_DFFR_Q_D_ALU_SUM_COUT),
      .I0  (rd_addr[7]),
      .I1  (wr_addr[7]),
      .I3  (\mem.0.0_CEA ),
      .SUM (wr_addr_DFFR_Q_D)
  );


  LUT4 #(
      .INIT(16'h0001)
  ) wr_addr_LUT4_I0 (
      .F (wr_addr_LUT4_I0_F),
      .I0(wr_addr[7]),
      .I1(wr_addr[6]),
      .I2(wr_addr[5]),
      .I3(wr_addr[4])
  );


  LUT4 #(
      .INIT(16'h1000)
  ) wr_addr_LUT4_I0_1 (
      .F (wr_addr_LUT4_I0_1_F[4]),
      .I0(wr_addr[3]),
      .I1(wr_addr[2]),
      .I2(wr_addr[1]),
      .I3(wr_addr[0])
  );


  DFFE wr_data_DFFE_Q (
      .CE (rd_en_DFFE_Q_CE),
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_data_DFFE_Q_D),
      .Q  (wr_data[7])
  );


  DFFE wr_data_DFFE_Q_1 (
      .CE (rd_en_DFFE_Q_CE),
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_data_DFFE_Q_1_D),
      .Q  (wr_data[6])
  );


  DFFE wr_data_DFFE_Q_2 (
      .CE (rd_en_DFFE_Q_CE),
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_data_DFFE_Q_2_D),
      .Q  (wr_data[4])
  );


  ALU #(
      .ALU_MODE(32'sd2)
  ) wr_data_DFFE_Q_2_D_ALU_SUM (
      .CIN (wr_data_DFFE_Q_3_D_ALU_SUM_COUT),
      .COUT(rd_en_DFFE_Q_D_ALU_SUM_CIN),
      .I0  (rd_addr[7]),
      .I1  (wr_data[4]),
      .I3  (\mem.0.0_CEA ),
      .SUM (wr_data_DFFE_Q_2_D)
  );


  DFFE wr_data_DFFE_Q_3 (
      .CE (rd_en_DFFE_Q_CE),
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_data_DFFE_Q_3_D),
      .Q  (wr_data[3])
  );


  ALU #(
      .ALU_MODE(32'sd2)
  ) wr_data_DFFE_Q_3_D_ALU_SUM (
      .CIN (wr_data_DFFE_Q_4_D_ALU_SUM_COUT),
      .COUT(wr_data_DFFE_Q_3_D_ALU_SUM_COUT),
      .I0  (rd_addr[7]),
      .I1  (wr_data[3]),
      .I3  (\mem.0.0_CEA ),
      .SUM (wr_data_DFFE_Q_3_D)
  );


  DFFE wr_data_DFFE_Q_4 (
      .CE (rd_en_DFFE_Q_CE),
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_data_DFFE_Q_4_D),
      .Q  (wr_data[2])
  );


  ALU #(
      .ALU_MODE(32'sd2)
  ) wr_data_DFFE_Q_4_D_ALU_SUM (
      .CIN (wr_data_DFFE_Q_5_D_ALU_SUM_COUT),
      .COUT(wr_data_DFFE_Q_4_D_ALU_SUM_COUT),
      .I0  (rd_addr[7]),
      .I1  (wr_data[2]),
      .I3  (\mem.0.0_CEA ),
      .SUM (wr_data_DFFE_Q_4_D)
  );


  DFFE wr_data_DFFE_Q_5 (
      .CE (rd_en_DFFE_Q_CE),
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_data_DFFE_Q_5_D),
      .Q  (wr_data[1])
  );


  ALU #(
      .ALU_MODE(32'sd2)
  ) wr_data_DFFE_Q_5_D_ALU_SUM (
      .CIN (wr_data_DFFE_Q_5_D_ALU_SUM_CIN),
      .COUT(wr_data_DFFE_Q_5_D_ALU_SUM_COUT),
      .I0  (rd_addr[7]),
      .I1  (wr_data[1]),
      .I3  (\mem.0.0_CEA ),
      .SUM (wr_data_DFFE_Q_5_D)
  );


  ALU #(
      .ALU_MODE(32'sd2)
  ) wr_data_DFFE_Q_5_D_ALU_SUM_CIN_ALU_COUT (
      .CIN (rd_addr[7]),
      .COUT(wr_data_DFFE_Q_5_D_ALU_SUM_CIN),
      .I0  (\mem.0.0_CEA ),
      .I1  (wr_data[0]),
      .I3  (\mem.0.0_CEA ),
      .SUM (wr_data_DFFE_Q_5_D_ALU_SUM_CIN_ALU_COUT_SUM)
  );


  DFFE wr_data_DFFE_Q_6 (
      .CE (rd_en_DFFE_Q_CE),
      .CLK(sys_clk_IBUF_I_O),
      .D  (wr_data_DFFE_Q_6_D),
      .Q  (wr_data[0])
  );


  LUT1 #(
      .INIT(2'h1)
  ) wr_data_DFFE_Q_6_D_LUT1_F (
      .F (wr_data_DFFE_Q_6_D),
      .I0(wr_data[0])
  );


  ALU #(
      .ALU_MODE(32'sd2)
  ) wr_data_DFFE_Q_D_ALU_SUM (
      .CIN (rd_en_DFFE_Q_D_ALU_SUM_COUT_ALU_CIN_COUT),
      .COUT(wr_data_DFFE_Q_D_ALU_SUM_COUT),
      .I0  (rd_addr[7]),
      .I1  (wr_data[7]),
      .I3  (\mem.0.0_CEA ),
      .SUM (wr_data_DFFE_Q_D)
  );
  assign \mem.0.0_ADA [0] = rd_addr[0];
  assign wr_addr_LUT4_I0_1_F[3:0] = {wr_addr[4], wr_addr[5], wr_addr[6], wr_addr[7]};
  assign \mem.0.0_DIA_1 [0] = \mem.0.0_DIA ;
  assign \mem.0.0_DOB_2 [0] = \mem.0.0_DOB_3 [0];
  assign \mem.0.0_DOB_1 [7:0] = {\mem.0.0_DOB_2 [7:1], \mem.0.0_DOB_3 [0]};
  assign \mem.0.0_DOA [8:0] = \mem.0.0_DOA_1 ;
  assign \mem.0.0_DOB [8:0] = {\mem.0.0_DOB_1 [8], \mem.0.0_DOB_2 [7:1], \mem.0.0_DOB_3 [0]};
  assign rd_addr[6:1] = {rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7]};
  assign rd_data[7:1] = 7'hxx;
  assign wr_data[5] = rd_en;
endmodule
