/* Generated by Yosys 0.61+112 (git sha1 ac427a79b-dirty, aarch64-apple-darwin23.5-clang++ 18.1.8 -fPIC -O3) */

(* hdlname = "main" *)
(* dynports =  1  *)
(* top =  1  *)
(* src = "main.v:3.1-62.10" *)
module main(sys_clk, probe_clk, probe_rd_en, probe_mem_out, probe_reg_out);
  (* src = "main.v:7.11-7.18" *)
  input sys_clk;
  wire sys_clk;
  (* src = "main.v:10.12-10.21" *)
  output probe_clk;
  wire probe_clk;
  (* src = "main.v:11.12-11.23" *)
  output probe_rd_en;
  wire probe_rd_en;
  (* src = "main.v:12.12-12.25" *)
  output probe_mem_out;
  wire probe_mem_out;
  (* src = "main.v:13.12-13.25" *)
  output probe_reg_out;
  wire probe_reg_out;
  (* force_downto = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:130.20-130.21" *)
  wire [1:0] \mem.0.0_ADA ;
  (* force_downto = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:130.20-130.21" *)
  wire [7:0] \mem.0.0_ADA_LUT2_I1_F ;
  wire \mem.0.0_CEA ;
  wire \mem.0.0_DIA ;
  wire [7:0] \mem.0.0_DIA_1 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/brams_map.v:261.14-261.17" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17" *)
  wire [17:0] \mem.0.0_DOA ;
  (* unused_bits = "0 1 2 3 4 5 6 7 8" *)
  wire [8:0] \mem.0.0_DOA_1 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/brams_map.v:262.14-262.17" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17" *)
  wire [17:0] \mem.0.0_DOB ;
  (* unused_bits = "1 2 3 4 5 6 7 8" *)
  wire [8:0] \mem.0.0_DOB_1 ;
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] \mem.0.0_DOB_2 ;
  (* force_downto = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:130.20-130.21" *)
  wire [2:0] \mem.0.0_DOB_3 ;
  wire \mem.0.0_DOB_3_DFFE_Q_1_D ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:169.9-169.11" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:163.9-163.11" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:157.9-157.11" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:157.13-157.15" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:163.13-163.15" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:157.9-157.11" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:157.13-157.15" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:169.13-169.15" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:163.9-163.11" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:157.9-157.11" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:157.13-157.15" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:163.13-163.15" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:157.9-157.11" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:157.13-157.15" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ;
  (* src = "main.v:32.24-32.31" *)
  wire [7:0] rd_addr;
  wire rd_addr_DFFE_Q_D;
  (* src = "main.v:33.13-33.20" *)
  wire [7:0] rd_data;
  wire sys_clk_IBUF_I_O;
  (* src = "main.v:29.24-29.31" *)
  wire [7:0] wr_addr;
  wire wr_addr_DFFR_Q_1_D;
  (* abc9_carry = 32'd1 *)
  (* src = "main.v:50.18-50.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire wr_addr_DFFR_Q_1_D_ALU_SUM_COUT;
  wire wr_addr_DFFR_Q_2_D;
  (* abc9_carry = 32'd1 *)
  (* src = "main.v:50.18-50.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire wr_addr_DFFR_Q_2_D_ALU_SUM_COUT;
  wire wr_addr_DFFR_Q_3_D;
  (* abc9_carry = 32'd1 *)
  (* src = "main.v:50.18-50.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire wr_addr_DFFR_Q_3_D_ALU_SUM_COUT;
  wire wr_addr_DFFR_Q_4_D;
  (* abc9_carry = 32'd1 *)
  (* src = "main.v:50.18-50.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire wr_addr_DFFR_Q_4_D_ALU_SUM_COUT;
  wire wr_addr_DFFR_Q_5_D;
  (* abc9_carry = 32'd1 *)
  (* src = "main.v:50.18-50.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire wr_addr_DFFR_Q_5_D_ALU_SUM_COUT;
  wire wr_addr_DFFR_Q_6_D;
  (* abc9_carry = 32'd1 *)
  (* src = "main.v:50.18-50.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire wr_addr_DFFR_Q_6_D_ALU_SUM_CIN;
  (* unused_bits = "0" *)
  wire wr_addr_DFFR_Q_6_D_ALU_SUM_CIN_ALU_COUT_SUM;
  (* abc9_carry = 32'd1 *)
  (* src = "main.v:50.18-50.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire wr_addr_DFFR_Q_6_D_ALU_SUM_COUT;
  wire wr_addr_DFFR_Q_7_D;
  wire wr_addr_DFFR_Q_D;
  (* abc9_carry = 32'd1 *)
  (* src = "main.v:50.18-50.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  (* unused_bits = "0" *)
  wire wr_addr_DFFR_Q_D_ALU_SUM_COUT;
  (* src = "main.v:30.13-30.20" *)
  wire [7:0] wr_data;
  wire wr_data_DFFE_Q_1_D;
  (* abc9_carry = 32'd1 *)
  (* src = "main.v:48.18-48.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire wr_data_DFFE_Q_1_D_ALU_SUM_COUT;
  wire wr_data_DFFE_Q_2_D;
  (* abc9_carry = 32'd1 *)
  (* src = "main.v:48.18-48.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire wr_data_DFFE_Q_2_D_ALU_SUM_COUT;
  wire wr_data_DFFE_Q_3_D;
  (* abc9_carry = 32'd1 *)
  (* src = "main.v:48.18-48.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire wr_data_DFFE_Q_3_D_ALU_SUM_COUT;
  wire wr_data_DFFE_Q_4_D;
  (* abc9_carry = 32'd1 *)
  (* src = "main.v:48.18-48.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire wr_data_DFFE_Q_4_D_ALU_SUM_COUT;
  wire wr_data_DFFE_Q_5_D;
  (* abc9_carry = 32'd1 *)
  (* src = "main.v:48.18-48.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire wr_data_DFFE_Q_5_D_ALU_SUM_COUT;
  wire wr_data_DFFE_Q_6_D;
  (* abc9_carry = 32'd1 *)
  (* src = "main.v:48.18-48.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire wr_data_DFFE_Q_6_D_ALU_SUM_CIN;
  (* unused_bits = "0" *)
  wire wr_data_DFFE_Q_6_D_ALU_SUM_CIN_ALU_COUT_SUM;
  (* abc9_carry = 32'd1 *)
  (* src = "main.v:48.18-48.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  wire wr_data_DFFE_Q_6_D_ALU_SUM_COUT;
  wire wr_data_DFFE_Q_7_D;
  wire wr_data_DFFE_Q_CE;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire wr_data_DFFE_Q_CE_MUX2_LUT5_O_I0;
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire wr_data_DFFE_Q_CE_MUX2_LUT5_O_I1;
  (* force_downto = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:130.20-130.21" *)
  wire [4:0] wr_data_DFFE_Q_CE_MUX2_LUT5_O_S0;
  wire wr_data_DFFE_Q_D;
  (* abc9_carry = 32'd1 *)
  (* src = "main.v:48.18-48.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_sim.v:938.25-938.29" *)
  (* unused_bits = "0" *)
  wire wr_data_DFFE_Q_D_ALU_SUM_COUT;
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/brams_map.v:278.4-299.3" *)
  DPX9B #(
    .BIT_WIDTH_0(32'd9),
    .BIT_WIDTH_1(32'd9),
    .BLK_SEL_0(3'h0),
    .BLK_SEL_1(3'h0),
    .INIT_RAM_00(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_01(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_02(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_03(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_04(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_05(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_06(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_07(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_08(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_09(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0A(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0B(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0C(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0D(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0E(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_0F(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_10(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_11(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_12(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_13(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_14(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_15(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_16(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_17(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_18(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_19(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1A(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1B(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1C(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1D(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1E(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_1F(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_20(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_21(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_22(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_23(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_24(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_25(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_26(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_27(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_28(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_29(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2A(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2B(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2C(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2D(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2E(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_2F(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_30(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_31(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_32(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_33(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_34(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_35(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_36(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_37(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_38(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_39(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3A(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3B(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3C(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3D(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3E(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .INIT_RAM_3F(288'h000000000000000000000000000000000000000000000000000000000000000000000000),
    .READ_MODE0(1'h0),
    .READ_MODE1(1'h0),
    .RESET_MODE("ASYNC"),
    .WRITE_MODE0(32'd2),
    .WRITE_MODE1(32'd2)
  ) \mem.0.0  (
    .ADA({ rd_addr[7], rd_addr[7], rd_addr[7], \mem.0.0_ADA_LUT2_I1_F [0], \mem.0.0_ADA_LUT2_I1_F [1], \mem.0.0_ADA_LUT2_I1_F [2], \mem.0.0_ADA_LUT2_I1_F [3], \mem.0.0_ADA_LUT2_I1_F [4], \mem.0.0_ADA_LUT2_I1_F [5], \mem.0.0_ADA_LUT2_I1_F [6], \mem.0.0_ADA [1], rd_addr[7], rd_addr[7], rd_addr[7] }),
    .ADB({ rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[0], rd_addr[7], rd_addr[7], rd_addr[7] }),
    .BLKSELA({ rd_addr[7], rd_addr[7], rd_addr[7] }),
    .BLKSELB({ rd_addr[7], rd_addr[7], rd_addr[7] }),
    .CEA(\mem.0.0_CEA ),
    .CEB(wr_data[5]),
    .CLKA(sys_clk_IBUF_I_O),
    .CLKB(sys_clk_IBUF_I_O),
    .DIA({ rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], 1'hx, \mem.0.0_DIA_1 [7:1], \mem.0.0_DIA  }),
    .DIB({ rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], 9'hxxx }),
    .DOA({ \mem.0.0_DOA [17:9], \mem.0.0_DOA_1  }),
    .DOB({ \mem.0.0_DOB [17:9], \mem.0.0_DOB_1 [8], \mem.0.0_DOB_2 [7:1], \mem.0.0_DOB_3 [0] }),
    .OCEA(\mem.0.0_CEA ),
    .OCEB(\mem.0.0_CEA ),
    .RESETA(rd_addr[7]),
    .RESETB(rd_addr[7]),
    .WREA(\mem.0.0_CEA ),
    .WREB(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \mem.0.0_ADA_DFF_Q  (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_addr[0]),
    .Q(\mem.0.0_ADA [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:139.23-140.26" *)
  LUT2 #(
    .INIT(4'h9)
  ) \mem.0.0_ADA_LUT2_I1  (
    .F(\mem.0.0_ADA_LUT2_I1_F [7]),
    .I0(rd_addr[0]),
    .I1(\mem.0.0_ADA [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \mem.0.0_ADA_LUT2_I1_F_DFF_Q  (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_addr[7]),
    .Q(\mem.0.0_ADA_LUT2_I1_F [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \mem.0.0_ADA_LUT2_I1_F_DFF_Q_1  (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_addr[6]),
    .Q(\mem.0.0_ADA_LUT2_I1_F [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \mem.0.0_ADA_LUT2_I1_F_DFF_Q_2  (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_addr[5]),
    .Q(\mem.0.0_ADA_LUT2_I1_F [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \mem.0.0_ADA_LUT2_I1_F_DFF_Q_3  (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_addr[4]),
    .Q(\mem.0.0_ADA_LUT2_I1_F [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \mem.0.0_ADA_LUT2_I1_F_DFF_Q_4  (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_addr[3]),
    .Q(\mem.0.0_ADA_LUT2_I1_F [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \mem.0.0_ADA_LUT2_I1_F_DFF_Q_5  (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_addr[2]),
    .Q(\mem.0.0_ADA_LUT2_I1_F [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \mem.0.0_ADA_LUT2_I1_F_DFF_Q_6  (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_addr[1]),
    .Q(\mem.0.0_ADA_LUT2_I1_F [6])
  );
  VCC \mem.0.0_CEA_VCC_V  (
    .V(\mem.0.0_CEA )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \mem.0.0_DIA_1_DFF_Q  (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_data[7]),
    .Q(\mem.0.0_DIA_1 [7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \mem.0.0_DIA_1_DFF_Q_1  (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_data[6]),
    .Q(\mem.0.0_DIA_1 [6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \mem.0.0_DIA_1_DFF_Q_2  (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_data[5]),
    .Q(\mem.0.0_DIA_1 [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \mem.0.0_DIA_1_DFF_Q_3  (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_data[4]),
    .Q(\mem.0.0_DIA_1 [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \mem.0.0_DIA_1_DFF_Q_4  (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_data[3]),
    .Q(\mem.0.0_DIA_1 [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \mem.0.0_DIA_1_DFF_Q_5  (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_data[2]),
    .Q(\mem.0.0_DIA_1 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \mem.0.0_DIA_1_DFF_Q_6  (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_data[1]),
    .Q(\mem.0.0_DIA_1 [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF \mem.0.0_DIA_DFF_Q  (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_data[0]),
    .Q(\mem.0.0_DIA )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \mem.0.0_DOB_3_DFFE_Q  (
    .CE(wr_data[5]),
    .CLK(sys_clk_IBUF_I_O),
    .D(\mem.0.0_DIA ),
    .Q(\mem.0.0_DOB_3 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \mem.0.0_DOB_3_DFFE_Q_1  (
    .CE(wr_data[5]),
    .CLK(sys_clk_IBUF_I_O),
    .D(\mem.0.0_DOB_3_DFFE_Q_1_D ),
    .Q(\mem.0.0_DOB_3 [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:172.14-172.54" *)
  MUX2_LUT8 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O  (
    .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0 ),
    .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1 ),
    .O(\mem.0.0_DOB_3_DFFE_Q_1_D ),
    .S0(\mem.0.0_ADA_LUT2_I1_F [7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:166.14-166.54" *)
  MUX2_LUT7 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O  (
    .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0 ),
    .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1 ),
    .O(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0 ),
    .S0(\mem.0.0_ADA_LUT2_I1_F [6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:160.14-160.54" *)
  MUX2_LUT6 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O  (
    .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ),
    .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ),
    .O(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0 ),
    .S0(\mem.0.0_ADA_LUT2_I1_F [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O  (
    .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
    .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
    .O(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ),
    .S0(\mem.0.0_ADA_LUT2_I1_F [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:152.41-152.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
    .I0(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:153.41-153.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F  (
    .F(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
    .I0(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O  (
    .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
    .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
    .O(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ),
    .S0(\mem.0.0_ADA_LUT2_I1_F [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:152.41-152.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
    .I0(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:153.41-153.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F  (
    .F(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
    .I0(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:160.14-160.54" *)
  MUX2_LUT6 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O  (
    .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ),
    .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ),
    .O(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1 ),
    .S0(\mem.0.0_ADA_LUT2_I1_F [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O  (
    .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
    .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
    .O(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ),
    .S0(\mem.0.0_ADA_LUT2_I1_F [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:152.41-152.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
    .I0(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:153.41-153.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F  (
    .F(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
    .I0(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O  (
    .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
    .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
    .O(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ),
    .S0(\mem.0.0_ADA_LUT2_I1_F [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:152.41-152.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
    .I0(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:170.42-170.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:153.41-153.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F  (
    .F(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
    .I0(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:166.14-166.54" *)
  MUX2_LUT7 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O  (
    .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0 ),
    .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1 ),
    .O(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1 ),
    .S0(\mem.0.0_ADA_LUT2_I1_F [6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:160.14-160.54" *)
  MUX2_LUT6 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O  (
    .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ),
    .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ),
    .O(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0 ),
    .S0(\mem.0.0_ADA_LUT2_I1_F [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O  (
    .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
    .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
    .O(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ),
    .S0(\mem.0.0_ADA_LUT2_I1_F [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:152.41-152.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT4 #(
    .INIT(16'h0001)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT4_F  (
    .F(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
    .I0(\mem.0.0_ADA_LUT2_I1_F [0]),
    .I1(\mem.0.0_ADA_LUT2_I1_F [1]),
    .I2(\mem.0.0_ADA_LUT2_I1_F [2]),
    .I3(\mem.0.0_ADA_LUT2_I1_F [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:153.41-153.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F  (
    .F(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
    .I0(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O  (
    .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
    .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
    .O(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ),
    .S0(\mem.0.0_ADA_LUT2_I1_F [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:152.41-152.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
    .I0(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:164.41-164.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:153.41-153.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F  (
    .F(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
    .I0(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:160.14-160.54" *)
  MUX2_LUT6 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O  (
    .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ),
    .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ),
    .O(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1 ),
    .S0(\mem.0.0_ADA_LUT2_I1_F [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O  (
    .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
    .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
    .O(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ),
    .S0(\mem.0.0_ADA_LUT2_I1_F [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:152.41-152.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
    .I0(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:158.41-158.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:153.41-153.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F  (
    .F(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
    .I0(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O  (
    .I0(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
    .I1(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
    .O(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ),
    .S0(\mem.0.0_ADA_LUT2_I1_F [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:152.41-152.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
    .I0(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:171.43-171.68|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:165.42-165.67|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:159.41-159.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:153.41-153.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F  (
    .F(\mem.0.0_DOB_3_DFFE_Q_1_D_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
    .I0(rd_addr[7])
  );
  (* keep = 32'd1 *)
  OBUF probe_clk_OBUF_O (
    .I(sys_clk_IBUF_I_O),
    .O(probe_clk)
  );
  (* keep = 32'd1 *)
  OBUF probe_mem_out_OBUF_O (
    .I(rd_addr[7]),
    .O(probe_mem_out)
  );
  (* keep = 32'd1 *)
  OBUF probe_rd_en_OBUF_O (
    .I(wr_data[5]),
    .O(probe_rd_en)
  );
  (* keep = 32'd1 *)
  OBUF probe_reg_out_OBUF_O (
    .I(rd_data[0]),
    .O(probe_reg_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:55.3-60.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE rd_addr_DFFE_Q (
    .CE(wr_data[5]),
    .CLK(sys_clk_IBUF_I_O),
    .D(rd_addr_DFFE_Q_D),
    .Q(rd_addr[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) rd_addr_DFFE_Q_D_LUT1_F (
    .F(rd_addr_DFFE_Q_D),
    .I0(rd_addr[0])
  );
  GND rd_addr_GND_G (
    .G(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'he2)
  ) rd_data_LUT3_F (
    .F(rd_data[0]),
    .I0(\mem.0.0_DOB_3 [0]),
    .I1(\mem.0.0_DOB_3 [1]),
    .I2(\mem.0.0_DOB_3 [2])
  );
  (* keep = 32'd1 *)
  IBUF sys_clk_IBUF_I (
    .I(sys_clk),
    .O(sys_clk_IBUF_I_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:44.3-52.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR wr_addr_DFFR_Q (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_addr_DFFR_Q_D),
    .Q(wr_addr[7]),
    .RESET(wr_data_DFFE_Q_CE)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:44.3-52.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR wr_addr_DFFR_Q_1 (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_addr_DFFR_Q_1_D),
    .Q(wr_addr[6]),
    .RESET(wr_data_DFFE_Q_CE)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:50.18-50.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) wr_addr_DFFR_Q_1_D_ALU_SUM (
    .CIN(wr_addr_DFFR_Q_2_D_ALU_SUM_COUT),
    .COUT(wr_addr_DFFR_Q_1_D_ALU_SUM_COUT),
    .I0(rd_addr[7]),
    .I1(wr_addr[6]),
    .I3(\mem.0.0_CEA ),
    .SUM(wr_addr_DFFR_Q_1_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:44.3-52.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR wr_addr_DFFR_Q_2 (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_addr_DFFR_Q_2_D),
    .Q(wr_addr[5]),
    .RESET(wr_data_DFFE_Q_CE)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:50.18-50.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) wr_addr_DFFR_Q_2_D_ALU_SUM (
    .CIN(wr_addr_DFFR_Q_3_D_ALU_SUM_COUT),
    .COUT(wr_addr_DFFR_Q_2_D_ALU_SUM_COUT),
    .I0(rd_addr[7]),
    .I1(wr_addr[5]),
    .I3(\mem.0.0_CEA ),
    .SUM(wr_addr_DFFR_Q_2_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:44.3-52.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR wr_addr_DFFR_Q_3 (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_addr_DFFR_Q_3_D),
    .Q(wr_addr[4]),
    .RESET(wr_data_DFFE_Q_CE)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:50.18-50.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) wr_addr_DFFR_Q_3_D_ALU_SUM (
    .CIN(wr_addr_DFFR_Q_4_D_ALU_SUM_COUT),
    .COUT(wr_addr_DFFR_Q_3_D_ALU_SUM_COUT),
    .I0(rd_addr[7]),
    .I1(wr_addr[4]),
    .I3(\mem.0.0_CEA ),
    .SUM(wr_addr_DFFR_Q_3_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:44.3-52.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR wr_addr_DFFR_Q_4 (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_addr_DFFR_Q_4_D),
    .Q(wr_addr[3]),
    .RESET(wr_data_DFFE_Q_CE)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:50.18-50.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) wr_addr_DFFR_Q_4_D_ALU_SUM (
    .CIN(wr_addr_DFFR_Q_5_D_ALU_SUM_COUT),
    .COUT(wr_addr_DFFR_Q_4_D_ALU_SUM_COUT),
    .I0(rd_addr[7]),
    .I1(wr_addr[3]),
    .I3(\mem.0.0_CEA ),
    .SUM(wr_addr_DFFR_Q_4_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:44.3-52.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR wr_addr_DFFR_Q_5 (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_addr_DFFR_Q_5_D),
    .Q(wr_addr[2]),
    .RESET(wr_data_DFFE_Q_CE)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:50.18-50.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) wr_addr_DFFR_Q_5_D_ALU_SUM (
    .CIN(wr_addr_DFFR_Q_6_D_ALU_SUM_COUT),
    .COUT(wr_addr_DFFR_Q_5_D_ALU_SUM_COUT),
    .I0(rd_addr[7]),
    .I1(wr_addr[2]),
    .I3(\mem.0.0_CEA ),
    .SUM(wr_addr_DFFR_Q_5_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:44.3-52.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR wr_addr_DFFR_Q_6 (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_addr_DFFR_Q_6_D),
    .Q(wr_addr[1]),
    .RESET(wr_data_DFFE_Q_CE)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:50.18-50.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) wr_addr_DFFR_Q_6_D_ALU_SUM (
    .CIN(wr_addr_DFFR_Q_6_D_ALU_SUM_CIN),
    .COUT(wr_addr_DFFR_Q_6_D_ALU_SUM_COUT),
    .I0(rd_addr[7]),
    .I1(wr_addr[1]),
    .I3(\mem.0.0_CEA ),
    .SUM(wr_addr_DFFR_Q_6_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:50.18-50.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) wr_addr_DFFR_Q_6_D_ALU_SUM_CIN_ALU_COUT (
    .CIN(rd_addr[7]),
    .COUT(wr_addr_DFFR_Q_6_D_ALU_SUM_CIN),
    .I0(\mem.0.0_CEA ),
    .I1(wr_addr[0]),
    .I3(\mem.0.0_CEA ),
    .SUM(wr_addr_DFFR_Q_6_D_ALU_SUM_CIN_ALU_COUT_SUM)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:44.3-52.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR wr_addr_DFFR_Q_7 (
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_addr_DFFR_Q_7_D),
    .Q(wr_addr[0]),
    .RESET(wr_data_DFFE_Q_CE)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) wr_addr_DFFR_Q_7_D_LUT1_F (
    .F(wr_addr_DFFR_Q_7_D),
    .I0(wr_addr[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:50.18-50.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) wr_addr_DFFR_Q_D_ALU_SUM (
    .CIN(wr_addr_DFFR_Q_1_D_ALU_SUM_COUT),
    .COUT(wr_addr_DFFR_Q_D_ALU_SUM_COUT),
    .I0(rd_addr[7]),
    .I1(wr_addr[7]),
    .I3(\mem.0.0_CEA ),
    .SUM(wr_addr_DFFR_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:44.3-52.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE wr_data_DFFE_Q (
    .CE(wr_data_DFFE_Q_CE),
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_data_DFFE_Q_D),
    .Q(wr_data[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:44.3-52.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE wr_data_DFFE_Q_1 (
    .CE(wr_data_DFFE_Q_CE),
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_data_DFFE_Q_1_D),
    .Q(wr_data[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:48.18-48.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) wr_data_DFFE_Q_1_D_ALU_SUM (
    .CIN(wr_data_DFFE_Q_2_D_ALU_SUM_COUT),
    .COUT(wr_data_DFFE_Q_1_D_ALU_SUM_COUT),
    .I0(rd_addr[7]),
    .I1(wr_data[6]),
    .I3(\mem.0.0_CEA ),
    .SUM(wr_data_DFFE_Q_1_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:44.3-52.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE wr_data_DFFE_Q_2 (
    .CE(wr_data_DFFE_Q_CE),
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_data_DFFE_Q_2_D),
    .Q(wr_data[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:48.18-48.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) wr_data_DFFE_Q_2_D_ALU_SUM (
    .CIN(wr_data_DFFE_Q_3_D_ALU_SUM_COUT),
    .COUT(wr_data_DFFE_Q_2_D_ALU_SUM_COUT),
    .I0(rd_addr[7]),
    .I1(wr_data[5]),
    .I3(\mem.0.0_CEA ),
    .SUM(wr_data_DFFE_Q_2_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:44.3-52.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE wr_data_DFFE_Q_3 (
    .CE(wr_data_DFFE_Q_CE),
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_data_DFFE_Q_3_D),
    .Q(wr_data[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:48.18-48.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) wr_data_DFFE_Q_3_D_ALU_SUM (
    .CIN(wr_data_DFFE_Q_4_D_ALU_SUM_COUT),
    .COUT(wr_data_DFFE_Q_3_D_ALU_SUM_COUT),
    .I0(rd_addr[7]),
    .I1(wr_data[4]),
    .I3(\mem.0.0_CEA ),
    .SUM(wr_data_DFFE_Q_3_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:44.3-52.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE wr_data_DFFE_Q_4 (
    .CE(wr_data_DFFE_Q_CE),
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_data_DFFE_Q_4_D),
    .Q(wr_data[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:48.18-48.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) wr_data_DFFE_Q_4_D_ALU_SUM (
    .CIN(wr_data_DFFE_Q_5_D_ALU_SUM_COUT),
    .COUT(wr_data_DFFE_Q_4_D_ALU_SUM_COUT),
    .I0(rd_addr[7]),
    .I1(wr_data[3]),
    .I3(\mem.0.0_CEA ),
    .SUM(wr_data_DFFE_Q_4_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:44.3-52.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE wr_data_DFFE_Q_5 (
    .CE(wr_data_DFFE_Q_CE),
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_data_DFFE_Q_5_D),
    .Q(wr_data[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:48.18-48.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) wr_data_DFFE_Q_5_D_ALU_SUM (
    .CIN(wr_data_DFFE_Q_6_D_ALU_SUM_COUT),
    .COUT(wr_data_DFFE_Q_5_D_ALU_SUM_COUT),
    .I0(rd_addr[7]),
    .I1(wr_data[2]),
    .I3(\mem.0.0_CEA ),
    .SUM(wr_data_DFFE_Q_5_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:44.3-52.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE wr_data_DFFE_Q_6 (
    .CE(wr_data_DFFE_Q_CE),
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_data_DFFE_Q_6_D),
    .Q(wr_data[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:48.18-48.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) wr_data_DFFE_Q_6_D_ALU_SUM (
    .CIN(wr_data_DFFE_Q_6_D_ALU_SUM_CIN),
    .COUT(wr_data_DFFE_Q_6_D_ALU_SUM_COUT),
    .I0(rd_addr[7]),
    .I1(wr_data[1]),
    .I3(\mem.0.0_CEA ),
    .SUM(wr_data_DFFE_Q_6_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:48.18-48.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) wr_data_DFFE_Q_6_D_ALU_SUM_CIN_ALU_COUT (
    .CIN(rd_addr[7]),
    .COUT(wr_data_DFFE_Q_6_D_ALU_SUM_CIN),
    .I0(\mem.0.0_CEA ),
    .I1(wr_data[0]),
    .I3(\mem.0.0_CEA ),
    .SUM(wr_data_DFFE_Q_6_D_ALU_SUM_CIN_ALU_COUT_SUM)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:44.3-52.6|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE wr_data_DFFE_Q_7 (
    .CE(wr_data_DFFE_Q_CE),
    .CLK(sys_clk_IBUF_I_O),
    .D(wr_data_DFFE_Q_7_D),
    .Q(wr_data[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) wr_data_DFFE_Q_7_D_LUT1_F (
    .F(wr_data_DFFE_Q_7_D),
    .I0(wr_data[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 wr_data_DFFE_Q_CE_MUX2_LUT5_O (
    .I0(wr_data_DFFE_Q_CE_MUX2_LUT5_O_I0),
    .I1(wr_data_DFFE_Q_CE_MUX2_LUT5_O_I1),
    .O(wr_data_DFFE_Q_CE),
    .S0(wr_data_DFFE_Q_CE_MUX2_LUT5_O_S0[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:152.41-152.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) wr_data_DFFE_Q_CE_MUX2_LUT5_O_I0_LUT1_F (
    .F(wr_data_DFFE_Q_CE_MUX2_LUT5_O_I0),
    .I0(rd_addr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:153.41-153.66|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT4 #(
    .INIT(16'h0001)
  ) wr_data_DFFE_Q_CE_MUX2_LUT5_O_I1_LUT4_F (
    .F(wr_data_DFFE_Q_CE_MUX2_LUT5_O_I1),
    .I0(wr_addr[7]),
    .I1(wr_addr[6]),
    .I2(wr_addr[5]),
    .I3(wr_addr[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT4 #(
    .INIT(16'h1000)
  ) wr_data_DFFE_Q_CE_MUX2_LUT5_O_S0_LUT4_F (
    .F(wr_data_DFFE_Q_CE_MUX2_LUT5_O_S0[4]),
    .I0(wr_addr[3]),
    .I1(wr_addr[2]),
    .I2(wr_addr[1]),
    .I3(wr_addr[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "main.v:48.18-48.29|/Users/user/.apio/packages/oss-cad-suite/libexec/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'sd2)
  ) wr_data_DFFE_Q_D_ALU_SUM (
    .CIN(wr_data_DFFE_Q_1_D_ALU_SUM_COUT),
    .COUT(wr_data_DFFE_Q_D_ALU_SUM_COUT),
    .I0(rd_addr[7]),
    .I1(wr_data[7]),
    .I3(\mem.0.0_CEA ),
    .SUM(wr_data_DFFE_Q_D)
  );
  assign \mem.0.0_ADA [0] = rd_addr[0];
  assign wr_data_DFFE_Q_CE_MUX2_LUT5_O_S0[3:0] = { wr_addr[4], wr_addr[5], wr_addr[6], wr_addr[7] };
  assign \mem.0.0_DIA_1 [0] = \mem.0.0_DIA ;
  assign \mem.0.0_DOB_2 [0] = \mem.0.0_DOB_3 [0];
  assign \mem.0.0_DOB_1 [7:0] = { \mem.0.0_DOB_2 [7:1], \mem.0.0_DOB_3 [0] };
  assign \mem.0.0_DOA [8:0] = \mem.0.0_DOA_1 ;
  assign \mem.0.0_DOB [8:0] = { \mem.0.0_DOB_1 [8], \mem.0.0_DOB_2 [7:1], \mem.0.0_DOB_3 [0] };
  assign rd_addr[6:1] = { rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7], rd_addr[7] };
  assign rd_data[7:1] = 7'hxx;
endmodule
